In [1]:
import numpy as np


In [2]:
lst=[1,2,3,4,5]
array=np.array(lst)

In [5]:
print(type(array))
array

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [4]:
type(array)

numpy.ndarray

In [6]:
array.shape()

TypeError: 'tuple' object is not callable

In [7]:
array.shape

(5,)

In [8]:
array.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
array.reshape(1,1,5)

array([[[1, 2, 3, 4, 5]]])

In [10]:
array.reshape(1,5,1)

array([[[1],
        [2],
        [3],
        [4],
        [5]]])

In [11]:
array

array([1, 2, 3, 4, 5])

In [12]:
array.reshape(1,3)

ValueError: cannot reshape array of size 5 into shape (1,3)

In [14]:
## multinested array

list1=[1,2,3,4,5]
list2=['a','b']
array1=np.array([list1,list2])
array1

<ipython-input-14-340d331811ed>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array1=np.array([list1,list2])


array([list([1, 2, 3, 4, 5]), list(['a', 'b'])], dtype=object)

In [26]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
array1=np.array([list1,list2])
array1
array1.shape

(2, 5)

In [24]:
#lists must be of same length or else it gives us the rows as no of lists but doesnt give no of columns value
list1=[1,2,3,4,5]
list2=[6,7,8]
list3=[6,7,8]
array1=np.array([list1,list2,list3])
array1

<ipython-input-24-db0d1ce8b96d>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array1=np.array([list1,list2,list3])


array([list([1, 2, 3, 4, 5]), list([6, 7, 8]), list([6, 7, 8])],
      dtype=object)

In [25]:
array1.shape

(3,)

In [27]:
list2=[6,7,8]
list3=['a','b','c']
array1=np.array([list2,list3])
array1

array([['6', '7', '8'],
       ['a', 'b', 'c']], dtype='<U11')

In [28]:
array1.shape

(2, 3)

In [30]:
#indexing
indexArray=np.array([[1,2,3,4,5],[2,3,4,5,6],[9,7,6,8,9]])
indexArray

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [31]:
indexArray[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [32]:
indexArray[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [33]:
indexArray[-1:-3,:]

array([], shape=(0, 5), dtype=int32)

In [34]:
indexArray[-1:,:]

array([[9, 7, 6, 8, 9]])

In [39]:
indexArray[-1::-1,:]

array([[9, 7, 6, 8, 9],
       [2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5]])

In [40]:
indexArray[-1::-1,-1::-1]

array([[9, 8, 6, 7, 9],
       [6, 5, 4, 3, 2],
       [5, 4, 3, 2, 1]])

In [41]:
indexArray[-1:-3:-1,-1::-1]

array([[9, 8, 6, 7, 9],
       [6, 5, 4, 3, 2]])

In [42]:
indexArray

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [43]:
indexArray[1:,3:]

array([[5, 6],
       [8, 9]])

In [44]:
indexArray[1:,2:4]

array([[4, 5],
       [6, 8]])

In [45]:
indexArray[1:2,1:4]

array([[3, 4, 5]])

In [47]:
#Arrange
arrayArrange=np.arange(0,10)
arrayArrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arrayArrange=np.arange(0,10,step=2,dtype="float")
arrayArrange

array([0., 2., 4., 6., 8.])

In [49]:
arrayArrange.reshape(5,1)

array([[0.],
       [2.],
       [4.],
       [6.],
       [8.]])

In [52]:
#linspace
arraylin=np.linspace(1,2,50,dtype='float')
arraylin

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [54]:
arraylin=np.linspace(1,10,50,dtype='int',endpoint=False,retstep=True)
arraylin

(array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
        4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8,
        8, 9, 9, 9, 9, 9]),
 0.18)

In [56]:
#copy and broadcasting
arrayIn=np.array([1,2,3,4])
arrayIn[2:]=5
arrayIn

array([1, 2, 5, 5])

In [57]:
arrayIn2=arrayIn
arrayIn2

array([1, 2, 5, 5])

In [58]:
arrayIn2[2:]=6

In [59]:
arrayIn2

array([1, 2, 6, 6])

In [60]:
arrayIn

array([1, 2, 6, 6])

In [61]:
#arrayIn gets updated too because they refer to same memory location, to avoid this we use copy() function
arrayNew=np.array([1,2,3,4,5])
arrayNew[2:]=5
arrayNew

array([1, 2, 5, 5, 5])

In [65]:
arrayNew2=arrayNew.copy(order='C')
arrayNew2

array([1, 2, 5, 5, 5])

In [66]:
#value doesnt change here
arrayNew2[2:]=6
print(arrayNew2)
print(arrayNew)

[1 2 6 6 6]
[1 2 5 5 5]


In [67]:
#exploratory functions
val=3
arrayNew<=2

array([ True,  True, False, False, False])

In [68]:
array[arrayNew<=2]

array([1, 2])

In [70]:
arrayNew*2

array([ 2,  4, 10, 10, 10])

In [71]:
#ones 
np.ones(1)

array([1.])

In [74]:
np.ones(1,dtype='int')

array([1])

In [75]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [76]:
#zeroes
np.zeros(4)

array([0., 0., 0., 0.])

In [77]:
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [78]:
#full
np.full(4,2)

array([2, 2, 2, 2])

In [80]:
np.full((4,2),(1,2))

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [82]:
#full_like
arr=[1,2,3]
np.full_like(arr,1)


array([1, 1, 1])

In [84]:
#random
np.random.rand()

0.05930611521855489

In [85]:
np.random.rand(1,10)

array([[0.47519879, 0.9784035 , 0.38628917, 0.82832543, 0.09560603,
        0.99818317, 0.43289383, 0.32932096, 0.83745255, 0.61622102]])

In [86]:
np.random.rand(3,3)

array([[0.65330034, 0.56324182, 0.94474512],
       [0.62760742, 0.4062185 , 0.62564846],
       [0.24077586, 0.03113634, 0.1921357 ]])

In [87]:
#random.randn() return sample values from standard normal distribution
np.random.randn()

0.03571810377213379

In [88]:
np.random.randn(2,3)

array([[-1.06355367, -0.89608198, -0.86388001],
       [ 1.78503135,  0.05226341,  0.82341684]])

In [90]:
#randint()
np.random.randint(3)

2

In [92]:
#Generate a 2 x 4 array of ints between 0 and 4
np.random.randint(5,size=(2,4))

array([[3, 2, 2, 0],
       [4, 1, 4, 2]])

In [94]:
np.random.randint(5,size=10)

array([1, 3, 1, 1, 2, 0, 2, 3, 1, 3])

In [96]:
np.random.randint(1,size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
#Generate a 1 x 3 array with 3 different upper bounds
np.random.randint(2,[3,4,100])

array([ 2,  3, 81])

In [99]:
#random sample
np.random.random_sample()

0.8115060940317079

In [102]:
np.random.random_sample((2,5))

array([[0.84454562, 0.06700165, 0.93142276, 0.067751  , 0.37231368],
       [0.08693552, 0.03513959, 0.7104122 , 0.69860415, 0.07275919]])